version: "3.9"
services:
  db:
    build:
      context: devops/postgres
      dockerfile: Dockerfile
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - "backend/.env"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000 #gunicorn --config gunicorn.conf.py
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3095:3095"
